apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web
  labels:
    app: nodejs-web
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodejs-web
  template:
    metadata:
      labels:
        app: nodejs-web
    spec:
      containers:
      - name: nodejs-web
        image: demoaksacademia.azurecr.io/nodejs-web:latest
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-web
spec:
  selector:
    app: nodejs-web
  ports:
    - port: 8089
      targetPort: 8089
  type: LoadBalancer
